name: apn_cache
description: In memory caching service for Flutter projects
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0
  equatable: ^2.0.3
  